language: clojure
lein: 2.7.1
before_install:
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash
script:
  - lein test
  - lein test :generative
  - lein with-profile dev,recent-clj test
# Workaround for https://github.com/travis-ci/travis-ci/issues/4691
sudo: required
jdk:
  - openjdk8
